name: CD — Deploy su HuggingFace

on:
  workflow_run:
    workflows: ["CI — Training and evaluation"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step di scaricamento dell'artifact
      # Con run-id: ${{ github.event.workflow_run.id }} viene detto di cercare l'artifact nel run della CI che ha triggerato CD
      # che è esattamente dove si trova il modello. A tal proposito viene passato anche il GITHUB_TOKEN, il quale serve specificamente 
      # per il download-artifact@v4, pocihé scaricare un artifact prodotto da un workflow diverso richiede autenticazione.
      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: sentiment-model
          path: ./models/sentiment_model/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      # Step di deploy del modello
      # In questo step sono necessari il nome della repo e un HF_Token con permesso di scrittura,
      # entrambi presenti nei github secrets
      - name: Push model to HuggingFace Hub
        env:
          HF_TOKEN:   ${{ secrets.HF_TOKEN }}
          HF_REPO:    ${{ secrets.HF_REPO }}
        run: python src/deploy.py