name: CD — Deploy su HuggingFace

on:
  workflow_run:
    workflows: ["CI — Training and evaluation"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: sentiment-model
          path: ./models/sentiment_model/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Push model to HuggingFace Hub
        env:
          HF_TOKEN:   ${{ secrets.HF_TOKEN }}
          HF_REPO:    ${{ secrets.HF_REPO }}
        run: python src/deploy.py