# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI — Training and evaluation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      dataset_name:
        description: "Hugging Face dataset to use"
        required: true
        default: "tweet_eval"
      dataset_config:
        description: "Dataset configuration"
        required: true
        default: "sentiment"
      train_samples:
        description: "Number of traning samples"
        required: true
        default: "1000"
      validation_samples:
        description: "Number of validation samples"
        required: true
        default: "1000"
      num_epochs:
        description: "Number of epochs for training"
        required: true
        default: "1"

permissions:
  contents: read

jobs:
  # JOB 1: UNIT e INTEGRATION TEST
  # Questi test vengono lanciati dopo ogni push per testare la validita del codice pushato
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Istruzione per lanciare il test
    - name: Run unit tests
      run: |
        pytest


  # JOB 2: ALLENAMENTO, TEST e DEPLOY del modello
  # Questo job viene lanciato solo manualmente per effettuare un retraining del modello
  train-and-deploy:
    runs-on: ubuntu-latest

    # Questa istruzione rende obbligatoria l'esecuzione del JOB 1 (test)
    # dell'esecuzione di questo job di allenamento
    needs: test

    # La seguente istruzione vincola il job ad essere triggerato manualmente
    if: github.event_name == 'workflow_dispatch'
    
    # Step per l'allenamento del modello
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Train model
      env:
        HF_REPO: ${{ secrets.HF_REPO }}
        DATASET_NAME: ${{ github.event.inputs.dataset_name   || 'tweet_eval' }}
        DATASET_CONFIG: ${{ github.event.inputs.dataset_config || 'sentiment' }}
        TRAIN_SAMPLES: ${{ github.event.inputs.train_samples  || '1000' }}
        VALIDATION_SAMPLES: ${{ github.event.inputs.validation_samples   || '1000' }}
        NUM_EPOCHS: ${{ github.event.inputs.num_epochs   || '3' }}
        PYTHONPATH: ${{ github.workspace }}
      run: python src/train.py

    # Step per la valutazione del modello su un bechmark
    - name: Evaluate model
      env:
        DATASET_NAME: ${{ github.event.inputs.dataset_name   || 'tweet_eval' }}
        DATASET_CONFIG: ${{ github.event.inputs.dataset_config || 'sentiment' }}
        HF_REPO: ${{ secrets.HF_REPO }}
        EVALUATE_MODE: "validate"
        PYTHONPATH: ${{ github.workspace }}
      run: python src/evaluate.py

    # Step per il deploy del modello
    - name: Push model to HuggingFace Hub
      env:
        # Questo step richiede HF_REPO e HF_TOKEN con permesso di scrittura
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_REPO: ${{ secrets.HF_REPO }}
        MODEL_PATH: "./models/sentiment_model"
        PYTHONPATH: ${{ github.workspace }}
      run: python src/deploy.py

    